defaults:
  working_directory: ~/repo
add_ghostscript_libs:
  run:
    command: |
      sudo apt-get update
      sudo apt-get --yes install ghostscript
      sudo apt-get --yes install libgs-dev
node_cache_key: v1-dependencies-{{ checksum "yarn.lock" }}
defaults_js:
  working_directory: ~/repo
  docker:
  - image: circleci/node:10.14.1
restore_node_cache:
  restore_cache:
    keys:
    - v1-dependencies-{{ checksum "yarn.lock" }}
save_node_cache:
  save_cache:
    paths:
    - node_modules
    key: v1-dependencies-{{ checksum "yarn.lock" }}
install_node_modules:
  run: yarn install --frozen-lockfile --no-progress --non-interactive --network-concurrency 1
version: 2
jobs:
  compile:
    working_directory: ~/repo
    docker:
    - image: circleci/node:10.14.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
    - run: yarn install --frozen-lockfile --no-progress --non-interactive --network-concurrency 1
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "yarn.lock" }}
    - run: yarn build
  tests:
    working_directory: ~/repo
    docker:
    - image: circleci/node:10.14.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
    - run: yarn install --frozen-lockfile --no-progress --non-interactive --network-concurrency 1
    - run:
        command: |
          sudo apt-get update
          sudo apt-get --yes install ghostscript
          sudo apt-get --yes install libgs-dev
    - run: yarn test
    - run: bash <(curl -s https://codecov.io/bash)
  lint:
    working_directory: ~/repo
    docker:
    - image: circleci/node:10.14.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
    - run: yarn install --frozen-lockfile --no-progress --non-interactive --network-concurrency 1
    - run: yarn lint
  lint-api:
    working_directory: ~/repo
    docker:
    - image: circleci/node:10.14.1
    steps:
    - checkout
    - run: npm install swagger-cli
    - run: npx swagger-cli validate openapi.yml
  danger:
    working_directory: ~/repo
    docker:
    - image: circleci/node:10.14.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
    - run: yarn install --frozen-lockfile --no-progress --non-interactive --network-concurrency 1
    - run: '[ -z "$DANGER_GITHUB_API_TOKEN" ] || yarn danger ci'
workflows:
  version: 2
  build:
    jobs:
    - compile
    - tests
    - lint
    - lint-api
    - danger:
        filters:
          branches:
            ignore: master
